export const contentConst = {
  // 视频管理
  CONTENT_MANAGE_VIDEO_LIST: '/video/list',
  CONTENT_MANAGE_VIDEO_EDIT: '/video/edit',
  CONTENT_MANAGE_VIDEO_DEL: '/video/del',
  CONTENT_MANAGE_VIDEO_CHANGE_STATUS: '/video/status/edit',
  // 视频类型
  CONTENT_MANAGE_VIDEO_TYPE_LIST: '/video/cate/list',
  CONTENT_MANAGE_VIDEO_TYPE_ADD: '/video/cate/add',
  CONTENT_MANAGE_VIDEO_TYPE_EDIT: '/video/cate/edit',
  CONTENT_MANAGE_VIDEO_TYPE_DEL: '/video/cate/del',
  // 轮播图
  CONTENT_MANAGE_BANNERS_LIST: '/banners/list',
  CONTENT_MANAGE_BANNERS_ADD: '/banners/add',
  CONTENT_MANAGE_BANNERS_EDIT: '/banners/edit',
  CONTENT_MANAGE_BANNERS_DEL: '/banners/del',
  CONTENT_MANAGE_BANNERS_CHANGE_STATUS: '/banners/status/edit',
  // 轮播图类型
  CONTENT_MANAGE_BANNERS_TYPE_LIST: '/banners/type/list',
  CONTENT_MANAGE_BANNERS_TYPE_ADD: '/banners/type/add',
  CONTENT_MANAGE_BANNERS_TYPE_EDIT: '/banners/type/edit',
  CONTENT_MANAGE_BANNERS_TYPE_DEL: '/banners/type/del',
  // 方案包
  CONTENT_MANAGE_PLAN_LIST: '/programme/list',
  CONTENT_MANAGE_PLAN_ADD: '/programme/add',
  CONTENT_MANAGE_PLAN_EDIT: '/programme/edit',
  CONTENT_MANAGE_PLAN_DELETE: '/programme/del',
  CONTENT_MANAGE_PLAN_TRANSLATE: '/programme/translate',
  CONTENT_MANAGE_PLAN_TRANSLATE_EDIT: '/programme/translate/edit',
  // 方案标签
  CONTENT_MANAGE_PLAN_TAG_LIST: '/programme/tag/list',
  CONTENT_MANAGE_PLAN_TAG_ADD: '/programme/tag/add',
  CONTENT_MANAGE_PLAN_TAG_EDIT: '/programme/tag/edit',
  CONTENT_MANAGE_PLAN_TAG_DEL: '/programme/tag/del',
  // 联赛包
  CONTENT_MANAGE_MATCH_COLLECTION_LIST: '/competition/conf/list',
  CONTENT_MANAGE_MATCH_COLLECTION_ADD: '/competition/conf/add',
  CONTENT_MANAGE_MATCH_COLLECTION_EDIT: '/competition/conf/edit',
  CONTENT_MANAGE_MATCH_COLLECTION_DEL: '/competition/conf/del',
  // 比赛列表
  CONTENT_MANAGE_MATCH_LIST: '/match/list',
  // 新闻管理
  CONTENT_MANAGE_NEWS_LIST: '/ios/news/list',
  CONTENT_MANAGE_NEWS_ADD: '/ios/news/add',
  CONTENT_MANAGE_NEWS_EDIT: '/ios/news/edit',
  CONTENT_MANAGE_NEWS_DEL: '/ios/news/del',
  CONTENT_MANAGE_NEWS_CATE: '/ios/news/cate',
};
